### ISSUE TITLE
Slide box

### ISSUE THREAD

**Issue by minowu** [VitualReaty/vue-human#26]

**Comment by minowu** [comment]
在根节点的时候，不需要用 ref 去标记这个节点，通过 this.$el 可以直接获得。

<img width="800" alt="screen shot 2016-11-07 at 11 27 44 am" src="https://cloud.githubusercontent.com/assets/1282787/20045575/439a0aee-a4dd-11e6-9cf0-f16f72702ac7.png">

相关文档：
[https://vuefe.cn/api/#vm-el](https://vuefe.cn/api/#vm-el)

**Comment by xxsue** [comment]
已修改

**Comment by xxsue** [comment]
修改了部分动画的实现。优化手机端动画的卡顿。
