### ISSUE TITLE
Slidebox bug with scroller

### ISSUE THREAD

**Issue by minowu** [VitualReaty/vue-human#50]
1. Slidebox bug with scroller.
2. Don't work in desktop browser.

**Comment by xxsue** [comment]
参考iOS的原因，SlideBox目前没有写PC端的滚动功能。可增加。

**Comment by minowu** [comment]
@xxsue 嗯，我们增加一下。

**Comment by xxsue** [comment]
已增加wheel函数。

**Comment by xxsue** [comment]
已完成，手机版的full修改为最大宽度为450px，也可以自定义设置（maxWidth）。
