### ISSUE TITLE
The style of date form's input needs to be modified

### ISSUE THREAD

**Issue by xxsue** [VitualReaty/vue-human#65]
![qq20161123-0](https://cloud.githubusercontent.com/assets/1849605/20553163/06a2d3fc-b18d-11e6-8a6e-7cbe7eede2bd.png)

web chrome 54.0.2840.98

**Comment by xxsue** [comment]
这个箭头部分需要删除吗 @minowu

**Comment by minowu** [comment]
@xxsue 游览器自带的，删除不了。

**Comment by xxsue** [comment]
@minowu 
我之前搜到了删这个的css。
````
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none !important;
  margin: 0;
}

input[type="number"] {
  -moz-appearance: textfield;
}
````

counter的input我之前加过这段，可以隐藏箭头。
不过不知道这个方法好不好。

**Comment by minowu** [comment]
好的，我试一下。
